version: 2
executorType: machine
jobs:
  build:
    environment:
      GOPATH: /home/circleci/.go_workspace
    working_directory: $GOPATH/src/github.com/linuxkit/rtf
    steps:
      - checkout
      - run: go get github.com/golang/lint/golint
      - run: go get github.com/gordonklaus/ineffassign
      - run: cd $GOPATH/src/github.com/linuxkit/rtf && make test
      - run: cd $GOPATH/src/github.com/linuxkit/rtf && make clean && make GOOS=darwin
      - run: cd $GOPATH/src/github.com/linuxkit/rtf && make clean && make GOOS=windows
